import type { PrintEstimate } from "../stl/estimate.js";
import { PRINT_HANDOFF_URL } from "../stl/config.js";

interface ViewerData {
  title: string;
  subtitle: string;
  /** query string for the STL route, e.g. "r=<gz>" (AI) or "s=<spec>" (template) */
  stlQuery: string;
  dims: { x: number; y: number; z: number };
  estimate: PrintEstimate;
}

/** Self-contained HTML page: shows the STL in 3D, with download + external print handoff. */
export function viewerPage(d: ViewerData): string {
  const title = d.title;
  const dims = `${d.dims.x.toFixed(1)} × ${d.dims.y.toFixed(1)} × ${d.dims.z.toFixed(1)} mm`;
  const stlPath = `/stl?${d.stlQuery}`;
  const dlPath = `${stlPath}&dl=1`;
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} — Printly</title>
<link rel="icon" type="image/png" href="/favicon.png">
<meta name="theme-color" content="#f4f1ea">
<meta property="og:type" content="website">
<meta property="og:title" content="${esc(title)} — Printly">
<meta property="og:description" content="A 3D-printable model generated by Printly. Preview it in 3D and download the STL.">
<meta property="og:image" content="https://printly3d.vercel.app/og.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://printly3d.vercel.app/og.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500&family=Hanken+Grotesk:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root{--paper:#f4f1ea;--ink:#17150f;--ink-2:#5c564a;--ink-3:#8a8271;--line:#e0dacd;--ember:#e0552b;--card:#faf8f3;
    --serif:'Fraunces',Georgia,serif;--sans:'Hanken Grotesk',system-ui,sans-serif;--mono:'JetBrains Mono',monospace}
  *{box-sizing:border-box}
  body{margin:0;font-family:var(--sans);font-size:15px;line-height:1.5;background:var(--paper);color:var(--ink);-webkit-font-smoothing:antialiased}
  header{padding:15px 22px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:13px;flex-wrap:wrap}
  header .home{display:flex;align-items:center;gap:9px;font-weight:600;text-decoration:none;color:var(--ink)}
  header .home img{width:26px;height:26px;border-radius:7px}
  header h1{font-family:var(--serif);font-weight:500;font-size:19px;margin:0}
  .tag{font-family:var(--mono);font-size:11.5px;color:var(--ink-3);border:1px solid var(--line);border-radius:999px;padding:3px 11px}
  #stage{width:100%;height:60vh;min-height:340px;display:block;background:radial-gradient(120% 120% at 50% 25%,#fbfaf6,#eae4d8);cursor:grab}
  #stage:active{cursor:grabbing}
  .panel{max-width:820px;margin:0 auto;padding:22px 22px 44px}
  .facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:12px 0}
  .fact{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px}
  .fact .k{font-family:var(--mono);font-size:11px;letter-spacing:.05em;color:var(--ink-3);text-transform:uppercase}
  .fact .v{font-family:var(--serif);font-size:22px;font-weight:500;margin-top:4px}
  .actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}
  a.btn{display:inline-block;text-decoration:none;padding:12px 20px;border-radius:11px;font-weight:600;font-size:14.5px;transition:transform .2s,box-shadow .2s}
  a.primary{background:var(--ink);color:var(--paper)}
  a.primary:hover{transform:translateY(-2px);box-shadow:0 10px 22px rgba(23,21,15,.16)}
  a.ghost{background:transparent;color:var(--ink);border:1px solid var(--line)}
  a.ghost:hover{border-color:var(--ink);transform:translateY(-2px)}
  .note{font-size:12.5px;color:var(--ink-3);margin-top:16px}
  .err{color:#b23b1e;padding:16px 22px;font-family:var(--mono);font-size:13px}
</style>
<script type="importmap">
{"imports":{"three":"https://unpkg.com/three@0.160.0/build/three.module.js","three/addons/":"https://unpkg.com/three@0.160.0/examples/jsm/"}}
</script>
</head><body>
<header>
  <a class="home" href="/"><img src="/icon.png" alt="">Printly</a>
  <h1>${esc(d.title)}</h1>
  <span class="tag">${esc(d.subtitle)}</span>
  <span class="tag">${dims}</span>
</header>
<canvas id="stage"></canvas>
<div class="panel">
  <div class="facts">
    <div class="fact"><div class="k">Size</div><div class="v">${dims}</div></div>
    <div class="fact"><div class="k">Material</div><div class="v">${d.estimate.grams} g</div></div>
    <div class="fact"><div class="k">Print time</div><div class="v">${d.estimate.printMinutes} min</div></div>
    <div class="fact"><div class="k">Print cost</div><div class="v">$${d.estimate.priceUsd.toFixed(2)}</div></div>
  </div>
  <div class="actions">
    <a class="btn primary" href="${dlPath}">Download STL</a>
    <a class="btn ghost" href="${esc(PRINT_HANDOFF_URL)}" target="_blank" rel="noopener noreferrer">Order a print ↗</a>
  </div>
  <p class="note">Estimate: ${esc(d.estimate.assumptions)}. "Order a print" opens an external print service — payment and shipping are handled there, not here.</p>
</div>
<script type="module">
  import * as THREE from 'three';
  import { STLLoader } from 'three/addons/loaders/STLLoader.js';
  import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

  const fail = (m) => document.body.insertAdjacentHTML('beforeend', '<p class="err">3D preview failed: ' + m + '. The STL download still works.</p>');
  window.addEventListener('error', (e) => fail(e.message || 'load error'));

  const canvas = document.getElementById('stage');
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(45, 1, 0.1, 5000);
  const controls = new OrbitControls(camera, canvas);
  controls.enableDamping = true; controls.dampingFactor = 0.08;
  scene.add(new THREE.HemisphereLight(0xffffff, 0xcfc7b4, 1.05));
  const key = new THREE.DirectionalLight(0xffffff, 1.5); key.position.set(2,3,2); scene.add(key);
  const rim = new THREE.DirectionalLight(0xffe6cf, 0.5); rim.position.set(-2,1,-2); scene.add(rim);

  function resize(){
    const w = canvas.clientWidth, h = canvas.clientHeight;
    renderer.setSize(w, h, false); camera.aspect = w/h; camera.updateProjectionMatrix();
  }
  new STLLoader().load('${stlPath}', (geo) => {
    geo.computeVertexNormals(); geo.center();
    const mat = new THREE.MeshStandardMaterial({ color: 0xcfc9bb, roughness: 0.82, metalness: 0.02 });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.rotation.x = -Math.PI/2;
    scene.add(mesh);
    geo.computeBoundingSphere();
    const r = geo.boundingSphere.radius;
    camera.position.set(r*1.5, r*1.2, r*1.9);
    controls.target.set(0,0,0); controls.update();
    resize();
    (function loop(){ requestAnimationFrame(loop); mesh.rotation.z += 0.0035; controls.update(); renderer.render(scene, camera); })();
  }, undefined, () => {
    document.body.insertAdjacentHTML('beforeend','<p class="err">Could not load model. The STL download still works.</p>');
  });
  window.addEventListener('resize', resize);
</script>
</body></html>`;
}

function esc(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}
